version: "3"

services:
  postgres_master:
    container_name: postgres-node1
    restart: always
    image: postgres:15.6
    environment:
      POSTGRES_PASSWORD: "password1"
    ports:
      - "5432:5432/tcp"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    volumes:
       - ./data/node1:/var/lib/postgresql/data        
    networks:
      db:

  postgres_slave:
    container_name: postgres-node2    
    image: postgres:15.6
    restart: always
    environment:
      POSTGRES_PASSWORD: "password2"
    ports:
      - "5433:5432/tcp"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    volumes:
       - ./data/node2:/var/lib/postgresql/data        
    networks:
      db:        
        
networks:
  db:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.9.0/24"